language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-18mode
  - rbx-18mode
  - rbx-19mode
  - ree
before_install:
  - gem update --system
  - gem --version # make sure rubygems actually were updated
before_script:
  - "psql -U postgres -c 'create database tree_test;'"
script: bundle exec rake test
gemfile:
  - gemfiles/activerecord2_3.gemfile
  - gemfiles/activerecord3_0.gemfile
  - gemfiles/activerecord3_1.gemfile
  - gemfiles/activerecord3_2.gemfile
  - gemfiles/activerecord4_0.gemfile
  - gemfiles/activerecord4_1.gemfile
matrix:
  exclude:
    - rvm: ree
      gemfile: gemfiles/activerecord3_2.gemfile
      gemfile: gemfiles/activerecord4_0.gemfile
      gemfile: gemfiles/activerecord4_1.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/activerecord3_2.gemfile
      gemfile: gemfiles/activerecord4_0.gemfile
      gemfile: gemfiles/activerecord4_1.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/activerecord3_2.gemfile
      gemfile: gemfiles/activerecord4_0.gemfile
      gemfile: gemfiles/activerecord4_1.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/activerecord3_2.gemfile
      gemfile: gemfiles/activerecord4_0.gemfile
      gemfile: gemfiles/activerecord4_1.gemfile
